---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  namespace: development
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  namespace: development
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: development
  name: imykhno
  email: imykhno@redhat.com
spec:
  profile:
    displayName: Ihor Mykhno
    email: imykhno@redhat.com
  memberOf: []
